### ISSUE TITLE
ci: Migrate leafo/gh-actions-lua to step-security maintained version

### ISSUE THREAD

**Issue by rbarkerSL** [hashgraph/hedera-the-graph#127]
## Background

Step-security is maintaining a list of actions with low scores. We need to update our third party actions to use
only actions with high scores. Step-security is now maintaining forked versions of utilized actions that should
be used. This story intends to update the actions listed below in [Step-Security Actions](#step-security-actions).

## Step-Security Action(s)

Update github actions with step-security maintained version

- [ ] Original Action: [leafo/gh-actions-lua](https://app.stepsecurity.io/github/hashgraph/actions/action-details/leafo%2Fgh-actions-lua) - Step Security Maintained Action: [step-security/gh-actions-lua](https://github.com/step-security/gh-actions-lua)

## Acceptance Criteria

- [ ] All required actions have been updated

**Comment by isavov** [comment]
Action is not actually used as it seems that it's not supported on self-hosted runners
