### ISSUE TITLE
Deployment of SS v2 subgraph

### ISSUE THREAD

**Issue by dougvk** [hashgraph/hedera-the-graph#132]
### Problem

Right now SSv2 is taking a while to index. I would like to deliver the subgraph to Messari to include in their quarterly reports.

### Solution

- Close this issue when SSv2 subgraph is indexed

**Comment by acuarica** [comment]
Hi @dougvk, thanks for sending this. I see SSv2 is healthy and indexing properly on `mainnet`. Let us know if we can mark this issue as completed.

**Comment by dougvk** [comment]
perfect, thanks! Yes!

**Comment by acuarica** [comment]
Perfect, thanks for confirming it. Closing this then. Feel free to reopen if you see any issues in the future.
