### ISSUE TITLE
Deploy: ICHI subgraph for 1 year

### ISSUE THREAD

**Issue by dougvk** [hashgraph/hedera-the-graph#133]
### Problem

Let's move forward with deploying and indexing the subgraph for ICHI found here: https://github.com/ichifarm/ichi-vaults-subgraphs/tree/master/hedera-v1-saucerswap. As per our agreement, ICHI will have access to use the index for a duration of one year.

### Solution

This will also be a good opportunity for us to observe how they utilize our The Graph service.

**Comment by acuarica** [comment]
Done, ICHI users were created and attributes were set accordingly.
